[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "vsbuildkit"
version = "0.1.0"
dependencies = [
  "packaging",
  "requests",
  "typer"
]
authors = [
  { name="Zero Point", email="msvsc-buildtools@itsallover.net.au" },
]
description = "A Microsoft Visual Studio Build Tools installer for Windows."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "tox"]

[project.urls]
Homepage = "https://github.com/ZeroPointReigen/msvs-buildtools"
Issues = "https://github.com/ZeroPointReigen/msvs-buildtools/issues"

[project.scripts]
vsbk = "vsbuildkit.cli:app"
