[tox]
env_list =
    py313
minversion = 4.25.0

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
    pytest-cov>=3.0.0
    diff-cover>=4.0.0
setenv =
    PYTHONPATH = {toxinidir}/src
allowlist_externals =
    git
commands =
    pytest -vv -s --cov=src/vsbuildkit --cov-report=xml --cov-report=term-missing {tty:--color=yes} \
    tests \
    {posargs}
    diff-cover --src-roots=src coverage.xml